export const CONST_EXTENSION_SETTING_FILE = '.ngI18nconfig';
export const CONST_TRANSUNIT_MEMORY_FILE_SUFFIX = 'xtm';
export const CONST_TRANSUNIT_MEMORY_FILE_TYPE = `.${CONST_TRANSUNIT_MEMORY_FILE_SUFFIX}`;